coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        branches:
          - main
        only_pulls: true
        paths:
          - src/backend
          - src/s3gw_ui_backend.py
